---
deployment:
    tasks:
        - export DEPLOYPATH=/home/tylerpor/repositories/tylerportfolio/dist/tyler-portfolio/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp style.css $DEPLOYPATH